version: '3.3'
services:
  db:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_DATABASE: 'llamadas_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'

    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: