export * from './Login'
export * from './Header'
export {default as Logo} from './Logo'
export {default as OperadorForm} from './Operador.tsx'
export {default as FormAction} from './FormAction.tsx'
export {default as Input} from './Input.tsx'
export {default as FormError} from './FormError.tsx'
export {default as SelectPaciente} from './SelectPaciente.tsx'
export {default as SeDeriba} from './SeDeriba.tsx'
export {default as EsBroma} from './EsBroma.tsx'
export {default as InfoText} from './InfoText.tsx'
export {default as SelectEspecialista} from './SelectEspecialista.tsx'
export {default as SelectLlamada} from './SelectLlamada.tsx'
export {default as EspecialistaForm} from './Especialista.tsx'
export {default as InputComentario} from './InputComentario.tsx'

